"""
Django settings for CMS project.

Generated by 'django-admin startproject' using Django 2.1.2.

For more information on this file, see
https://docs.djangoproject.com/en/2.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.1/ref/settings/
"""

import os
import pymysql

pymysql.install_as_MySQLdb()
# os.environ['DJANGO_SETTINGS_MODULE'] = 'mysite.settings'
# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'a*4_vcejt%gl@04^4flwaqx=17l-akb+7*-r_^dn7x5%re)c=b'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True
# DEBUG = False

ALLOWED_HOSTS = ['*', ]

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.sites',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_comments',
    'mycms',
    'DjangoUeditor',

]
SITE_ID = 1

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'CMS.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        # 这个路径是共用模板路径，如果是在app李米娜创建了模板，则在view里面app_xxx.html
        'DIRS': [os.path.join(BASE_DIR, 'templates').replace('\\', '/'), ],
        # 'DIRS': [BASE_DIR, 'templates'],
        # 'DIRS': [BASE_DIR, 'templates',],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'CMS.wsgi.application'

# Database
# https://docs.djangoproject.com/en/2.1/ref/settings/#databases
DATABASES = {
    # 'default': {
    #     'ENGINE': 'django.db.backends.sqlite3',
    #     'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    # }
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'cms',
        'USER': 'wanghs',
        'PASSWORD': '123',
        'HOST': 'localhost',
        'PORT': '3306',
    }

}

# Password validation
# https://docs.djangoproject.com/en/2.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/2.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_L10N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.1/howto/static-files/

# 访问的url，其他人可以通过这个路由访问资源
STATIC_URL = '/static/'
# 项目部署的时候会将所有的静态文件归到这个文件夹里面
STATIC_ROOT = os.path.join(BASE_DIR, 'collect_static')
# import dj_database_url
# DATABASES['default'] = dj_database_url.config(default='mysql://wanghs:123456@localhost/cms')
TEMPLATE_DIRS = (
    os.path.join(BASE_DIR, 'templates'),

)

'''
设置公共的static文件夹，可以跨app使用，按照project下的static找，找不到再从每个app找，惰性查找，找到了就会停。
#在使用css的时候，如果有这个STATICFILES_DIRS,那么在网页寻找资源就会先从这个static文件夹开始找，然后再到app里面的static文件找
不会到collect_static文件夹里面去找，注释了STATICFILES_DIRS的时候才会到这个文件夹寻找
'''
# 设置公共的static文件夹，可以跨app使用，按照project下的static找，找不到再从每个app找，惰性查找，找到了就会停
#在使用css的时候，如果有这个STATICFILES_DIRS,那么在网页寻找资源就会先从这个static文件夹开始找，然后再到app里面的static文件找
STATICFILES_DIRS = (
    os.path.join(BASE_DIR, 'static'),
)

MEDIA_URL = '/media/'

MEDIA_ROOT = os.path.join(BASE_DIR, 'collect_media')
