# Generated by Django 2.1.2 on 2019-11-13 09:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mycms', '0002_auto_20191113_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cms',
            name='create_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='cms',
            name='update_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
