# Generated by Django 2.1.2 on 2019-11-17 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycms', '0003_auto_20191113_1720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cms',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='cms',
            name='update_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
