# Generated by Django 2.1.2 on 2019-11-18 06:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mycms', '0004_auto_20191117_2132'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': '板块', 'verbose_name_plural': '板块'},
        ),
        migrations.AlterModelOptions(
            name='cms',
            options={'verbose_name': '发表内容', 'verbose_name_plural': '发表内容'},
        ),
        migrations.AlterModelOptions(
            name='cms_user',
            options={'verbose_name': '用户', 'verbose_name_plural': '用户'},
        ),
        migrations.AddField(
            model_name='cms',
            name='category',
            field=models.ForeignKey(default=33, on_delete=django.db.models.deletion.CASCADE, to='mycms.Category'),
            preserve_default=False,
        ),
    ]
