# Generated by Django 2.1.2 on 2019-11-27 06:24

import DjangoUeditor.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mycms', '0005_auto_20191118_1429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cms',
            name='content',
            field=DjangoUeditor.models.UEditorField(blank=True, verbose_name='内容'),
        ),
    ]
