# Generated by Django 2.1.2 on 2019-12-02 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycms', '0006_auto_20191127_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cms_user',
            name='photo',
            field=models.ImageField(default='img/1.jpg', upload_to='upload_imgs/'),
        ),
    ]
