# Generated by Django 2.1.2 on 2019-12-05 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycms', '0007_auto_20191202_1426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cms',
            name='ranking',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='cms',
            name='view_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='cms_user',
            name='photo',
            field=models.ImageField(default='/img/1.jpg', upload_to='upload_imgs/'),
        ),
    ]
